package com.klypt.ui.common

data class CountryInfo(
    val code: String,
    val name: String,
    val dialCode: String
)

object CountryCodeData {
    val countries = listOf(
        CountryInfo("AD", "Andorra", "+376"),
        CountryInfo("AE", "United Arab Emirates", "+971"),
        CountryInfo("AF", "Afghanistan", "+93"),
        CountryInfo("AG", "Antigua and Barbuda", "+1-268"),
        CountryInfo("AI", "Anguilla", "+1-264"),
        CountryInfo("AL", "Albania", "+355"),
        CountryInfo("AM", "Armenia", "+374"),
        CountryInfo("AO", "Angola", "+244"),
        CountryInfo("AR", "Argentina", "+54"),
        CountryInfo("AS", "American Samoa", "+1-684"),
        CountryInfo("AT", "Austria", "+43"),
        CountryInfo("AU", "Australia", "+61"),
        CountryInfo("AW", "Aruba", "+297"),
        CountryInfo("AZ", "Azerbaijan", "+994"),
        CountryInfo("BA", "Bosnia and Herzegovina", "+387"),
        CountryInfo("BB", "Barbados", "+1-246"),
        CountryInfo("BD", "Bangladesh", "+880"),
        CountryInfo("BE", "Belgium", "+32"),
        CountryInfo("BF", "Burkina Faso", "+226"),
        CountryInfo("BG", "Bulgaria", "+359"),
        CountryInfo("BH", "Bahrain", "+973"),
        CountryInfo("BI", "Burundi", "+257"),
        CountryInfo("BJ", "Benin", "+229"),
        CountryInfo("BM", "Bermuda", "+1-441"),
        CountryInfo("BN", "Brunei", "+673"),
        CountryInfo("BO", "Bolivia", "+591"),
        CountryInfo("BR", "Brazil", "+55"),
        CountryInfo("BS", "Bahamas", "+1-242"),
        CountryInfo("BT", "Bhutan", "+975"),
        CountryInfo("BW", "Botswana", "+267"),
        CountryInfo("BY", "Belarus", "+375"),
        CountryInfo("BZ", "Belize", "+501"),
        CountryInfo("CA", "Canada", "+1"),
        CountryInfo("CD", "Democratic Republic of the Congo", "+243"),
        CountryInfo("CF", "Central African Republic", "+236"),
        CountryInfo("CG", "Republic of the Congo", "+242"),
        CountryInfo("CH", "Switzerland", "+41"),
        CountryInfo("CI", "Côte d'Ivoire", "+225"),
        CountryInfo("CL", "Chile", "+56"),
        CountryInfo("CM", "Cameroon", "+237"),
        CountryInfo("CN", "China", "+86"),
        CountryInfo("CO", "Colombia", "+57"),
        CountryInfo("CR", "Costa Rica", "+506"),
        CountryInfo("CU", "Cuba", "+53"),
        CountryInfo("CV", "Cape Verde", "+238"),
        CountryInfo("CY", "Cyprus", "+357"),
        CountryInfo("CZ", "Czech Republic", "+420"),
        CountryInfo("DE", "Germany", "+49"),
        CountryInfo("DJ", "Djibouti", "+253"),
        CountryInfo("DK", "Denmark", "+45"),
        CountryInfo("DM", "Dominica", "+1-767"),
        CountryInfo("DO", "Dominican Republic", "+1-809"),
        CountryInfo("DZ", "Algeria", "+213"),
        CountryInfo("EC", "Ecuador", "+593"),
        CountryInfo("EE", "Estonia", "+372"),
        CountryInfo("EG", "Egypt", "+20"),
        CountryInfo("ES", "Spain", "+34"),
        CountryInfo("ET", "Ethiopia", "+251"),
        CountryInfo("FI", "Finland", "+358"),
        CountryInfo("FJ", "Fiji", "+679"),
        CountryInfo("FK", "Falkland Islands", "+500"),
        CountryInfo("FM", "Micronesia", "+691"),
        CountryInfo("FO", "Faroe Islands", "+298"),
        CountryInfo("FR", "France", "+33"),
        CountryInfo("GA", "Gabon", "+241"),
        CountryInfo("GB", "United Kingdom", "+44"),
        CountryInfo("GD", "Grenada", "+1-473"),
        CountryInfo("GE", "Georgia", "+995"),
        CountryInfo("GF", "French Guiana", "+594"),
        CountryInfo("GG", "Guernsey", "+44"),
        CountryInfo("GH", "Ghana", "+233"),
        CountryInfo("GI", "Gibraltar", "+350"),
        CountryInfo("GL", "Greenland", "+299"),
        CountryInfo("GM", "Gambia", "+220"),
        CountryInfo("GN", "Guinea", "+224"),
        CountryInfo("GP", "Guadeloupe", "+590"),
        CountryInfo("GQ", "Equatorial Guinea", "+240"),
        CountryInfo("GR", "Greece", "+30"),
        CountryInfo("GT", "Guatemala", "+502"),
        CountryInfo("GU", "Guam", "+1-671"),
        CountryInfo("GW", "Guinea-Bissau", "+245"),
        CountryInfo("GY", "Guyana", "+592"),
        CountryInfo("HK", "Hong Kong", "+852"),
        CountryInfo("HN", "Honduras", "+504"),
        CountryInfo("HR", "Croatia", "+385"),
        CountryInfo("HT", "Haiti", "+509"),
        CountryInfo("HU", "Hungary", "+36"),
        CountryInfo("ID", "Indonesia", "+62"),
        CountryInfo("IE", "Ireland", "+353"),
        CountryInfo("IL", "Israel", "+972"),
        CountryInfo("IM", "Isle of Man", "+44"),
        CountryInfo("IN", "India", "+91"),
        CountryInfo("IO", "British Indian Ocean Territory", "+246"),
        CountryInfo("IQ", "Iraq", "+964"),
        CountryInfo("IR", "Iran", "+98"),
        CountryInfo("IS", "Iceland", "+354"),
        CountryInfo("IT", "Italy", "+39"),
        CountryInfo("JE", "Jersey", "+44"),
        CountryInfo("JM", "Jamaica", "+1-876"),
        CountryInfo("JO", "Jordan", "+962"),
        CountryInfo("JP", "Japan", "+81"),
        CountryInfo("KE", "Kenya", "+254"),
        CountryInfo("KG", "Kyrgyzstan", "+996"),
        CountryInfo("KH", "Cambodia", "+855"),
        CountryInfo("KI", "Kiribati", "+686"),
        CountryInfo("KM", "Comoros", "+269"),
        CountryInfo("KN", "Saint Kitts and Nevis", "+1-869"),
        CountryInfo("KP", "North Korea", "+850"),
        CountryInfo("KR", "South Korea", "+82"),
        CountryInfo("KW", "Kuwait", "+965"),
        CountryInfo("KY", "Cayman Islands", "+1-345"),
        CountryInfo("KZ", "Kazakhstan", "+7"),
        CountryInfo("LA", "Laos", "+856"),
        CountryInfo("LB", "Lebanon", "+961"),
        CountryInfo("LC", "Saint Lucia", "+1-758"),
        CountryInfo("LI", "Liechtenstein", "+423"),
        CountryInfo("LK", "Sri Lanka", "+94"),
        CountryInfo("LR", "Liberia", "+231"),
        CountryInfo("LS", "Lesotho", "+266"),
        CountryInfo("LT", "Lithuania", "+370"),
        CountryInfo("LU", "Luxembourg", "+352"),
        CountryInfo("LV", "Latvia", "+371"),
        CountryInfo("LY", "Libya", "+218"),
        CountryInfo("MA", "Morocco", "+212"),
        CountryInfo("MC", "Monaco", "+377"),
        CountryInfo("MD", "Moldova", "+373"),
        CountryInfo("ME", "Montenegro", "+382"),
        CountryInfo("MF", "Saint Martin", "+590"),
        CountryInfo("MG", "Madagascar", "+261"),
        CountryInfo("MH", "Marshall Islands", "+692"),
        CountryInfo("MK", "North Macedonia", "+389"),
        CountryInfo("ML", "Mali", "+223"),
        CountryInfo("MM", "Myanmar", "+95"),
        CountryInfo("MN", "Mongolia", "+976"),
        CountryInfo("MO", "Macao", "+853"),
        CountryInfo("MP", "Northern Mariana Islands", "+1-670"),
        CountryInfo("MQ", "Martinique", "+596"),
        CountryInfo("MR", "Mauritania", "+222"),
        CountryInfo("MS", "Montserrat", "+1-664"),
        CountryInfo("MT", "Malta", "+356"),
        CountryInfo("MU", "Mauritius", "+230"),
        CountryInfo("MV", "Maldives", "+960"),
        CountryInfo("MW", "Malawi", "+265"),
        CountryInfo("MX", "Mexico", "+52"),
        CountryInfo("MY", "Malaysia", "+60"),
        CountryInfo("MZ", "Mozambique", "+258"),
        CountryInfo("NA", "Namibia", "+264"),
        CountryInfo("NC", "New Caledonia", "+687"),
        CountryInfo("NE", "Niger", "+227"),
        CountryInfo("NF", "Norfolk Island", "+672"),
        CountryInfo("NG", "Nigeria", "+234"),
        CountryInfo("NI", "Nicaragua", "+505"),
        CountryInfo("NL", "Netherlands", "+31"),
        CountryInfo("NO", "Norway", "+47"),
        CountryInfo("NP", "Nepal", "+977"),
        CountryInfo("NR", "Nauru", "+674"),
        CountryInfo("NU", "Niue", "+683"),
        CountryInfo("NZ", "New Zealand", "+64"),
        CountryInfo("OM", "Oman", "+968"),
        CountryInfo("PA", "Panama", "+507"),
        CountryInfo("PE", "Peru", "+51"),
        CountryInfo("PF", "French Polynesia", "+689"),
        CountryInfo("PG", "Papua New Guinea", "+675"),
        CountryInfo("PH", "Philippines", "+63"),
        CountryInfo("PK", "Pakistan", "+92"),
        CountryInfo("PL", "Poland", "+48"),
        CountryInfo("PM", "Saint Pierre and Miquelon", "+508"),
        CountryInfo("PN", "Pitcairn", "+870"),
        CountryInfo("PR", "Puerto Rico", "+1"),
        CountryInfo("PS", "Palestine", "+970"),
        CountryInfo("PT", "Portugal", "+351"),
        CountryInfo("PW", "Palau", "+680"),
        CountryInfo("PY", "Paraguay", "+595"),
        CountryInfo("QA", "Qatar", "+974"),
        CountryInfo("RE", "Réunion", "+262"),
        CountryInfo("RO", "Romania", "+40"),
        CountryInfo("RS", "Serbia", "+381"),
        CountryInfo("RU", "Russia", "+7"),
        CountryInfo("RW", "Rwanda", "+250"),
        CountryInfo("SA", "Saudi Arabia", "+966"),
        CountryInfo("SB", "Solomon Islands", "+677"),
        CountryInfo("SC", "Seychelles", "+248"),
        CountryInfo("SD", "Sudan", "+249"),
        CountryInfo("SE", "Sweden", "+46"),
        CountryInfo("SG", "Singapore", "+65"),
        CountryInfo("SH", "Saint Helena", "+290"),
        CountryInfo("SI", "Slovenia", "+386"),
        CountryInfo("SJ", "Svalbard and Jan Mayen", "+47"),
        CountryInfo("SK", "Slovakia", "+421"),
        CountryInfo("SL", "Sierra Leone", "+232"),
        CountryInfo("SM", "San Marino", "+378"),
        CountryInfo("SN", "Senegal", "+221"),
        CountryInfo("SO", "Somalia", "+252"),
        CountryInfo("SR", "Suriname", "+597"),
        CountryInfo("SS", "South Sudan", "+211"),
        CountryInfo("ST", "São Tomé and Príncipe", "+239"),
        CountryInfo("SV", "El Salvador", "+503"),
        CountryInfo("SX", "Sint Maarten", "+1-721"),
        CountryInfo("SY", "Syria", "+963"),
        CountryInfo("SZ", "Eswatini", "+268"),
        CountryInfo("TC", "Turks and Caicos Islands", "+1-649"),
        CountryInfo("TD", "Chad", "+235"),
        CountryInfo("TG", "Togo", "+228"),
        CountryInfo("TH", "Thailand", "+66"),
        CountryInfo("TJ", "Tajikistan", "+992"),
        CountryInfo("TK", "Tokelau", "+690"),
        CountryInfo("TL", "Timor-Leste", "+670"),
        CountryInfo("TM", "Turkmenistan", "+993"),
        CountryInfo("TN", "Tunisia", "+216"),
        CountryInfo("TO", "Tonga", "+676"),
        CountryInfo("TR", "Turkey", "+90"),
        CountryInfo("TT", "Trinidad and Tobago", "+1-868"),
        CountryInfo("TV", "Tuvalu", "+688"),
        CountryInfo("TW", "Taiwan", "+886"),
        CountryInfo("TZ", "Tanzania", "+255"),
        CountryInfo("UA", "Ukraine", "+380"),
        CountryInfo("UG", "Uganda", "+256"),
        CountryInfo("US", "United States", "+1"),
        CountryInfo("UY", "Uruguay", "+598"),
        CountryInfo("UZ", "Uzbekistan", "+998"),
        CountryInfo("VA", "Vatican City", "+379"),
        CountryInfo("VC", "Saint Vincent and the Grenadines", "+1-784"),
        CountryInfo("VE", "Venezuela", "+58"),
        CountryInfo("VG", "British Virgin Islands", "+1-284"),
        CountryInfo("VI", "United States Virgin Islands", "+1-340"),
        CountryInfo("VN", "Vietnam", "+84"),
        CountryInfo("VU", "Vanuatu", "+678"),
        CountryInfo("WF", "Wallis and Futuna", "+681"),
        CountryInfo("WS", "Samoa", "+685"),
        CountryInfo("YE", "Yemen", "+967"),
        CountryInfo("YT", "Mayotte", "+262"),
        CountryInfo("ZA", "South Africa", "+27"),
        CountryInfo("ZM", "Zambia", "+260"),
        CountryInfo("ZW", "Zimbabwe", "+263")
    )
}
